/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tadeo
 */
public class Productos extends javax.swing.JFrame {

    /**
     * Creates new form Productos
     */
    public Productos() {
        initComponents();
        tablas();
    }
    public void tablas(){
         try{
        PreparedStatement ps = null;
        ResultSet rs=null;
        Conexiones.Conexion objetoConexion = new Conexiones.Conexion();
        String consulta1="SELECT idproductos,producto,disponibles,productosTot,Precio FROM sistema_ventas.productos;";
        ps=objetoConexion.establecerConexion().prepareStatement(consulta1);
        rs=ps.executeQuery();
        JTable tabla = Tabla;
        DefaultTableModel model = (DefaultTableModel)tabla.getModel();
       model.setRowCount(0);
       while(rs.next()){
           Object[] Columnas = {
               rs.getObject("idproductos"),
               rs.getObject("producto"),
               rs.getObject("disponibles"),
               rs.getObject("productosTot"),
               rs.getObject("Precio")
           };
           model.addRow(Columnas);
       }
    }catch(Exception e){
        //JOptionPane.showMessageDialog(null,"No se pudieron mostrar los libros. ");
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDisponibles = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtProductosTot = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(221, 230, 237));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("nombre del producto: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 108, 180, 22));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 42, 1073, 10));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 142, 165, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Precio del producto: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 170, -1));
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 160, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Ingrese los productos aregados al almacen:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 240, -1));
        jPanel1.add(txtDisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 160, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 561, 1048, 10));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Disponibles", "Almacen", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 82, 616, -1));

        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 450, 200, -1));

        btnRegresar.setText("MENU");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 496, 196, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Ingrese el limite del almacenaje:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 180, -1));
        jPanel1.add(txtProductosTot, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 160, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        com.mycompany.sistema_ventas.Menu llamar =new com.mycompany.sistema_ventas.Menu();
        llamar.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // En este boton se agregara los datos de un producto, verificara si existe y si existe aumentara la cantidad, 
        //pero si no exite creara un nuevo objeto
        
        try{
            
            if(txtNombre.getText().isEmpty() && txtPrecio.getText().isEmpty() && txtDisponibles.getText().isEmpty() && txtProductosTot.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Ingrese un valor en las cajas ");
        }else{
                PreparedStatement ps=null;
            ResultSet rs=null;
            
            Conexiones.Conexion objetoConexion = new Conexiones.Conexion();
            String consultaProdu="SELECT producto,disponibles,productosTot FROM sistema_ventas.productos WHERE producto=?;";
            ps=objetoConexion.establecerConexion().prepareStatement(consultaProdu);
            
            ps.setString(1, txtNombre.getText());
            
            rs=ps.executeQuery();
            
            if(rs.next()){
                String nombreProdu=rs.getString("producto");
                int productosDispo=Integer.valueOf(rs.getString("disponibles"));
                int totalProdu=Integer.valueOf(rs.getString("productosTot"));
                JOptionPane.showMessageDialog(null, "Ya existe el producto: "+nombreProdu+", hay disponibles: "+productosDispo+", y el limite es de: "+totalProdu);
                //Ahora se ejecutara una consulta para actualizar la cantidad del producto ya existente 
                int producto =Integer.valueOf(txtDisponibles.getText());
                int suma=productosDispo+producto;
                
                
                if(suma>totalProdu){
                    JOptionPane.showMessageDialog(null,"No puede ingresar "+suma+" cuando el limite es de: "+totalProdu);
                }else{
                     //Ahora se ejecutara una consulta para actualizar la cantidad del producto ya existente 
                     String updProdu="UPDATE sistema_ventas.productos SET disponibles=? WHERE producto=?;";
                    ps=objetoConexion.establecerConexion().prepareStatement(updProdu);
                    
                    ps.setString(1,String.valueOf(suma));
                    ps.setString(2, txtNombre.getText());
                    
                    int numF=ps.executeUpdate();
                    
                    if(numF>0){
                        //Se actualizo tu producto
                        tablas();
                    }
                    
                    JOptionPane.showMessageDialog(null,"Si puedes ingresar "+suma+" cuando el limite es de: "+totalProdu);
                }
                
                
            }else{
                JOptionPane.showMessageDialog(null, "Ese producto no existe, se agregara,");
                //Ahora se agregara un nuevo producto a la lista 
                String agregarProdu="INSERT INTO sistema_ventas.productos(producto,disponibles,productosTot,Precio) VALUES (?,?,?,?);";
                ps=objetoConexion.establecerConexion().prepareStatement(agregarProdu);
                
                ps.setString(1, txtNombre.getText());
                ps.setString(2, txtDisponibles.getText());
                ps.setString(3, txtProductosTot.getText());
                ps.setString(4, txtPrecio.getText());
                int numFilas =ps.executeUpdate();
                
                if(numFilas>0){
                     JOptionPane.showMessageDialog(null, "El producto ya se agrego: "+txtNombre.getText()+" $"+txtPrecio.getText()+", cant: "+txtDisponibles.getText()+", limite: "+txtProductosTot.getText());
                     tablas();
                }
                
            }
            }
            
            
        }catch(Exception e){
            
            
        }
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtDisponibles;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtProductosTot;
    // End of variables declaration//GEN-END:variables
}
