/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tadeo
 */
public class Semanal extends javax.swing.JFrame {

    /**
     * Creates new form Semanal
     */
    public Semanal() {
        initComponents();
        tablas();
    }
    
    public void tablas(){
         try{
        PreparedStatement ps = null;
        ResultSet rs=null;
        Conexiones.Conexion objetoConexion = new Conexiones.Conexion();
        String consulta1="SELECT idDia,Fecha,ganancia FROM sistema_ventas.semana;";
        ps=objetoConexion.establecerConexion().prepareStatement(consulta1);
        rs=ps.executeQuery();
        JTable tabla = Tabla;
        DefaultTableModel model = (DefaultTableModel)tabla.getModel();
       model.setRowCount(0);
       while(rs.next()){
           Object[] Columnas = {
               rs.getObject("idDia"),
               rs.getObject("Fecha"),
               rs.getObject("ganancia")
           };
           model.addRow(Columnas);
       }
    }catch(Exception e){
        JOptionPane.showMessageDialog(null,"No se pudieron mostrar las ventas. ");
    }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();
        btnTotal = new javax.swing.JButton();
        btnHistorial = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(221, 230, 237));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Fecha", "Ganancia"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabla);

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TOTAL DEL DIA");

        lblTotal.setForeground(new java.awt.Color(0, 0, 0));
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotal.setText("0");
        lblTotal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnMenu.setText("MENU");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        btnTotal.setText("TOTAL");
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });

        btnHistorial.setText("Agregar a historial");
        btnHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialActionPerformed(evt);
            }
        });

        jButton1.setText("Venta Total");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnHistorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 887, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(181, 181, 181))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
                        .addGap(26, 26, 26))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 921, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        com.mycompany.sistema_ventas.Menu llamar =new com.mycompany.sistema_ventas.Menu();

        llamar.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        // TODO add your handling code here:
        //Aqui solamente voy a realizar las operaciones para obtener el valor ganado en la semana 
        try{
            PreparedStatement ps=null;
            ResultSet rs=null;
            int suma=0;
            int cont=1;
            Conexiones.Conexion objetoConexion = new Conexiones.Conexion();
            for( cont=1;cont<=6;cont++){
                String consultaVenta="SELECT ganancia FROM sistema_ventas.semana WHERE idDia=?;";
                ps=objetoConexion.establecerConexion().prepareStatement(consultaVenta);
                
                ps.setString(1,String.valueOf(cont));
                
                rs=ps.executeQuery();
                
                if(rs.next()){
                    int ganancias=Integer.valueOf(rs.getString("ganancia"));
                    suma=suma+ganancias;
                
                }
            }
            lblTotal.setText(String.valueOf(suma));
            
        }catch(Exception e ){
            JOptionPane.showMessageDialog(null, "No se pudo ");
        }
    }//GEN-LAST:event_btnTotalActionPerformed

    private void btnHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialActionPerformed
        // TODO add your handling code here:
        
        try{
            PreparedStatement ps=null;
            ResultSet rs=null;
            Conexiones.Conexion objetoConexion = new Conexiones.Conexion();
            if(lblTotal.getText().equals("0")){
                JOptionPane.showMessageDialog(null, "Precione primero el boton (TOTAL) para agregar a la tabla ");
            }else{
                //En este else se agregara en una tabla nueva todos los datos de la semana para despues eliminarlos 
               //Primeramente en la consulta verificara si la tabla de semana ya almaceno los 6 dias por eso mismo se buscara si ya 
               //existe el dia o el recorte numero 6
               
               String verificar ="SELECT idDia FROM sistema_ventas.semana WHERE idDia =?;";
               ps=objetoConexion.establecerConexion().prepareStatement(verificar);
               
               ps.setString(1,"6");
               
               rs=ps.executeQuery();
               
               if(rs.next()){
                   JOptionPane.showMessageDialog(null, "Ahora si puedes agregar a la tabla los valores semanales");
                   
                   //Primeramente se buscara y atraera el valor enla posicion 1 de la fecha de la tebla ventatotal 
                   String aumentarFecha="SELECT fecha FROM sistema_ventas.ventatotal WHERE idVentaTotal=?;";
                   ps=objetoConexion.establecerConexion().prepareStatement(aumentarFecha);
                   
                   ps.setString(1,"1");
                   
                   rs=ps.executeQuery();
                   
                   if(rs.next()){
                       int contador=Integer.valueOf(rs.getString("fecha"));
                       JOptionPane.showMessageDialog(null, "El contador esta en: "+contador);
                       //Ahora se aumentara el contador en 6 para poder sumar lo obtenido en todas las semanas registradas con un update
                       String agregarFecha ="UPDATE sistema_ventas.ventatotal SET fecha=? WHERE idVentaTotal=?;";
                       ps=objetoConexion.establecerConexion().prepareStatement(agregarFecha);
                       int suma=contador+6;
                       ps.setString(1,String.valueOf(suma));
                       ps.setString(2,"1");
                       
                       int numFilas=ps.executeUpdate();
                       
                       if(numFilas>0){
                           //Ahora se atraeran los datos de las ventas diarias de la tabla semana en un bucle for para despues agregarlas a la tabla
                           //ventatotal
                           int cont=1;
                           for(cont=1;cont<7;cont++){
                               
                               String ventasDiaria="SELECT Fecha,ganancia FROM sistema_ventas.semana WHERE idDia=?;";
                               ps=objetoConexion.establecerConexion().prepareStatement(ventasDiaria);
                               
                               ps.setString(1,String.valueOf(cont));
                               
                               rs=ps.executeQuery();
                               
                               if(rs.next()){
                                   String fecha=rs.getString("Fecha");
                                   String ganancia=rs.getString("ganancia");
                                   
                                   
                                   
                                   //Ahora se hace el insert a la tabla de ventatotal
                                   
                                   String agregarVentas="INSERT INTO sistema_ventas.ventatotal(fecha,ganancia) VALUES (?,?);";
                                   ps=objetoConexion.establecerConexion().prepareStatement(agregarVentas);
                                   
                                   ps.setString(1,fecha);
                                   ps.setString(2,ganancia);
                                   
                                   int nnn=ps.executeUpdate();
                                   
                                   if(nnn>0){
                                       JOptionPane.showMessageDialog(null, "Se agrego en tablas");
                                       if (cont==6){
                                           //Ahora lo que sedebe de hacer es eliminar la tabla se semana para que se reinicie el ciclo por asi decirlo
                                           
                                           String borrarSemana="DELETE FROM sistema_ventas.semana ;";
                                           ps=objetoConexion.establecerConexion().prepareStatement(borrarSemana);
                                           
                                           
                                           int numF=ps.executeUpdate();
                                           
                                           if(numF>0){
                                               JOptionPane.showMessageDialog(null, "Se borro la tabla semana ");
                                               
                                               String actualizarID="ALTER TABLE sistema_ventas.semana AUTO_INCREMENT=?;";
                                               ps=objetoConexion.establecerConexion().prepareStatement(actualizarID);
                                               
                                               ps.setInt(1,1);
                                               
                                               ps.executeUpdate();
                                               
                                               tablas();
                                           }
                                           
                                       }
                                   }
                                   
                                   
                               }
                               
                           }
                           
                       }
                       
                   }
                   
                   
               }else{
                    JOptionPane.showMessageDialog(null, "Aun no puedes hacer el recorte semanal, te faltan dias ");
               }
               
               
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Ocurrio un error ");
        }
    }//GEN-LAST:event_btnHistorialActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Login obj1=new Login();
        obj1.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Semanal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Semanal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Semanal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Semanal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Semanal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton btnHistorial;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnTotal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblTotal;
    // End of variables declaration//GEN-END:variables
}
